mark=int(input())
if(mark < 25): print("F")
elif(mark < 45 and mark <= 25): print("E")
elif(mark < 50 and mark <= 45): print("D")
elif(mark < 60 and mark <= 50): print("C")
elif(mark < 80 and mark <= 60): print("B")
elif(mark >= 80): print("A")
