f_a = int(input())
s_a = int(input())
t_a = int(input())
youngest=min(f_a, s_a, t_a)
oldest=max(f_a,s_a,t_a)
print("Youngest ", end='')
if(youngest==f_a): print("First")
elif(youngest==s_a): print("Second")
else: print("Third")
print("Oldest ", end='')
if(oldest==f_a): print("First")
elif(oldest==s_a): print("Second")
else: print("Third")
